version: '3.7'

services:

  currency-exchange:
    image: in28min/mmv2-currency-exchange-service:0.0.1-SNAPSHOT
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka

  naming-server:
    image: in28min/mmv2-naming-server:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    networks:
      - currency-network

  currency-conversion:
    image: in28min/mmv2-currency-conversion-service:0.0.1-SNAPSHOT
    ports:
      - "8100:8100"
    networks:
      - currency-network
    environment:
      eureka.client.serviceUrl.defaultZone: http://naming-server:8761/eureka
networks:
  currency-network: